# Data Wrangling
#going from raw data to neat data (lab data being so neat and going to raw data)

Data wrangling is an important factor in WFC 70. It will be a major aspect in aiding in your Data Story, and in any future class in which you will need to utilize data. However, it can be a bit confusing as to how to tie everything together. This module is meant to aid you through knowing how to apply certain data wrangling features. 


## Review

First, we will go over a quick overview of the tools in Tidyverse which allow you to data wrangle. The main ones utilized in this class are:

- filter
- joins
- select 

### Filter 

Filter, as the name suggests, selects only the rows which meets the conditions you want. This is helpful if you want to select only a particular species in a big data set.

### Joins

Joins combines two data sets into a singular data set through a common factor. For example, in Lab 6, we utilized left_join, and it is it the most commonly used join command.

- left_join → keeps all observations in x 
- right_join → keeps all observations in y 
- full_join → keeps all observations in x and y 

This is an article which goes deeper into joins if you are interested in playing around! The best way to learn is to also play around with your code and inputting the different joins to see what changes.

https://dplyr.tidyverse.org/reference/mutate-joins.html 

### Select

As the name suggests, select will only the columns of the data set you want to focus on. This is helpful in a large data set to only select certain columns such as weight, sex, length, etc.

Now that we have done a quick review of some of the essential codes needed for Data Wrangling, we now question how to tie them together for the Data Story.

## Tying Everything Together



